# Module 7 — Promotion Lift Model
# Owner: ML Pod A+B / AI Pod
# Description: Model diagnostics for the XGBoost promotion-lift model plus
#              the grounded AI analyst narrative (generated on demand via
#              the shared narrative service / guardrail).

import gradio as gr
import plotly.graph_objects as go

from dashboard.analytics.common.promotion_loader import get_promotion_loader
from dashboard.components import ui
from ai.services import narrative_service


def _responder_bar(summary, ascending: bool, n: int = 8):
    fig = go.Figure()
    if summary.empty:
        fig.update_layout(**ui.plotly_layout(300))
        return fig
    s = (summary.sort_values("mean_lift_pct", ascending=ascending)
         .head(n).iloc[::-1])
    fig.add_trace(go.Bar(
        y=s["sku_id"].astype(str), x=s["mean_lift_pct"], orientation="h",
        marker_color=(ui.ACCENTS[2] if ascending else ui.ACCENT),
        hovertemplate="SKU %{y}<br>%{x:.1f}% lift<extra></extra>",
    ))
    fig.update_layout(**ui.plotly_layout(
        300, xaxis_title="Mean lift %", yaxis_title="SKU"))
    return fig


def build_promotion_lift_model_tab():
    """Render Module 7 inside a running gr.Blocks context."""
    with gr.Tab("7. Promotion Lift Model"):
        loader = get_promotion_loader()
        ctx = loader.load_context()
        summary = loader.load_summary()

        if not ctx and summary.empty:
            gr.HTML(ui.warn(
                "⚠️ No promotion model diagnostics found. Run "
                "<code>ml/promotions/promotion_lift_model.ipynb</code>."))
            return

        metrics = ctx.get("metrics", {})
        gr.HTML(ui.header(
            "Promotion Lift Model — Module 7",
            f"Diagnostics for <b>{metrics.get('model_type', 'the lift model')}"
            "</b>. Out-of-sample metrics from time-series cross-validation; "
            "errors are in sales units."))

        gr.HTML(ui.kpi_cards([
            ("OOS MAE", f"{metrics.get('oos_mae', float('nan')):,.1f}",
             "mean abs error"),
            ("OOS RMSE", f"{metrics.get('oos_rmse', float('nan')):,.1f}",
             "penalises spikes"),
            ("OOS sMAPE", f"{metrics.get('oos_smape_pct', float('nan')):,.1f}%",
             "scaled pct error"),
            ("OOS R²", f"{metrics.get('oos_r2', float('nan')):,.3f}",
             "variance explained"),
            ("Median lift", f"{metrics.get('median_lift_pct', float('nan')):,.1f}%",
             f"{metrics.get('total_skus', 0)} SKUs"),
        ]))

        with gr.Row():
            with gr.Column():
                gr.Markdown("#### Top responders")
                gr.Plot(value=_responder_bar(summary, ascending=False),
                        show_label=False, container=False)
            with gr.Column():
                gr.Markdown("#### Weakest responders")
                gr.Plot(value=_responder_bar(summary, ascending=True),
                        show_label=False, container=False)

        gr.Markdown("#### AI analyst narrative")
        gr.Markdown(
            "<sub>Generated by the shared AI service, grounded in the model's "
            "context JSON and post-processed by the hallucination guardrail "
            "(numbers verified; reply labelled).</sub>")
        narr_btn = gr.Button("🧠 Generate lift narrative", variant="primary")
        narr_out = gr.Markdown()
        narr_btn.click(lambda: narrative_service.generate_lift_narrative(),
                       None, narr_out)


if __name__ == "__main__":
    with gr.Blocks(title="Promotion Lift Model") as demo:
        build_promotion_lift_model_tab()
    demo.launch()
